### ISSUE TITLE
Add "Lorem ipsum dolor sit amet." text to the first paragraph of the text

### ISSUE THREAD

**Issue by kutsan** [diegofelipece/mussum-ipsum#2]
Starting the dummy text with "Lorem ipsum dolor sit amet." sentence kind of standard way to do that even the following texts are not Latin. Especially customers will not confuse about that since they know it's dummy and will be replaced with actually content.

**Comment by diegofelipece** [comment]
Thanks for your comment @kutsan. I got your point, but I don't believe we should change that, because the script was made to serve a custom Dummy text generator called Mussum Ipsum (something like a brazilian version of the [Slipsum](http://slipsum.com/). But, anyway, with a simple configuration on the **mainQuote** you can change that. For example:

``` javascript
var loremIpsum = mIpsum({
     mainQuote: "Lorem Ipsum dolor sit ammet."
});
```
This will change the start from "Mussum Ipsum, vidis litro abertis", for the classic Lorem Ipsum :)
